# Generated by Django 3.1.7 on 2021-03-25 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 12, 27, 48, 716858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 12, 27, 48, 716858, tzinfo=utc)),
        ),
    ]
