# Generated by Django 3.1.7 on 2021-03-25 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210325_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 12, 32, 12, 487419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 12, 32, 12, 487419, tzinfo=utc)),
        ),
    ]
