# Generated by Django 3.1.7 on 2021-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='end_of_sales',
            field=models.DateField(blank=True, null=True),
        ),
    ]
