# Generated by Django 3.1.7 on 2021-03-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210326_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portal.employee'),
        ),
    ]
