# Generated by Django 3.2.5 on 2021-07-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_booking_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mother_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.company'),
        ),
    ]
