# Generated by Django 3.1.7 on 2021-03-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210325_1327'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portal.company'),
        ),
    ]
