# Generated by Django 3.1.7 on 2021-03-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210325_1332'),
        ('accounts', '0002_responsible_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='portal.company'),
        ),
    ]
