# Generated by Django 3.1.7 on 2021-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210325_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
