# Generated by Django 3.1.7 on 2021-03-26 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210325_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
