# Generated by Django 3.2.5 on 2021-07-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_company_mother_company'),
        ('info_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.service'),
        ),
    ]
